### ISSUE TITLE
Include Crashlog into a custom ruby app

### ISSUE THREAD

**Issue by betacar** [crashlog/crashlog#14]
I want to include CrashLog into a frameworless ruby app. It's a ruby daemon app. I don't find any instructions or tutorials for it.

**Comment by ivanvanderbyl** [comment]
Hi Carlos,

This is easy, do the usual `CrashLog.configure` stuff, then wrap the code you want to rescue to crashlog as follows:

``` ruby
begin
  # Do something dangerous
rescue => e
  CrashLog.notify(e)
end
```
