### ISSUE TITLE
Clicking link in email fails to show backtrace

### ISSUE THREAD

**Issue by camfowler** [crashlog/crashlog#4]
The "[View full backtrace](http://mandrillapp.com/track/click.php?u=10820415&id=ea4ddf312c4b459989376056304d319d&url=http%3A%2F%2Fcrashlog.io%2Fprojects%2F0165933f-4fed-4579-93be-8d1436ede7b2%2Fissues%2F05993360-a9d2-4be2-87eb-2eed57973c09&url_id=1207253497&tags=238701,238705)" link in the email refers to a page which doesnt actually show the backtrace (see screenshot):

https://www.evernote.com/shard/s41/sh/1229e9ba-5fc5-4c25-bd20-3e25bda3865f/af1c8e7803d4bedc670f8af6e76f5a0c

If I then click on the exception from the web app, it shows the correct backtrace:
https://www.evernote.com/shard/s41/sh/cbc12126-5c10-4f35-a164-b019d9d310be/b4d756f7ab75bc2ca780591c2e56f26f

**Comment by ivanvanderbyl** [comment]
Ah I see, it looks like a bug in our Ember app. I'll fix it today.

Thanks for reporting it Cameron.

**Comment by ivanvanderbyl** [comment]
Hey @camfowler this issue should be resolved now. We made quite a few updates to the UI over the weekend.
