### ISSUE TITLE
Incompatible with Rails 3.1.x

### ISSUE THREAD

**Issue by austinthecoder** [crashlog/crashlog#9]
Adding this gem to a Rails 3.1.8 app and bundling gives:

``` ruby
Bundler could not find compatible versions for gem "multi_json":
  In Gemfile:
    rails (= 3.1.8) ruby depends on
      multi_json (< 1.3, >= 1.0) ruby

    crashlog (~> 1.0.4) ruby depends on
      multi_json (1.3.7)
```

**Comment by ivanvanderbyl** [comment]
Thanks for reporting that. I'll see if we can push out a fix this morning. We locked to 1.3+ because it has a major API change.

**Comment by ivanvanderbyl** [comment]
@austinthecoder can you point your Gemfile to git://github.com/crashlog/crashlog.git and let me know if it is fixed. If so I''ll release 1.0.5

**Comment by austinthecoder** [comment]
This works. Thanks.
